# Generated by Django 5.1.3 on 2024-11-30 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Aceh', 'Aceh'), ('Sumatera Utara', 'Sumatera Utara'), ('Sumatera Barat', 'Sumatera Barat'), ('Riau', 'Riau'), ('Jambi', 'Jambi'), ('Sumatera Selatan', 'Sumatera Selatan'), ('Bengkulu', 'Bengkulu'), ('Lampung', 'Lampung'), ('Kepulauan Bangka Belitung', 'Kepulauan Bangka Belitung'), ('Kepulauan Riau', 'Kepulauan Riau'), ('DKI Jakarta', 'DKI Jakarta'), ('Jawa Barat', 'Jawa Barat'), ('Jawa Tengah', 'Jawa Tengah'), ('DI Yogyakarta', 'DI Yogyakarta'), ('Jawa Timur', 'Jawa Timur'), ('Banten', 'Banten'), ('Bali', 'Bali'), ('Nusa Tenggara Barat', 'Nusa Tenggara Barat'), ('Nusa Tenggara Timur', 'Nusa Tenggara Timur'), ('Kalimantan Barat', 'Kalimantan Barat'), ('Kalimantan Tengah', 'Kalimantan Tengah'), ('Kalimantan Selatan', 'Kalimantan Selatan'), ('Kalimantan Timur', 'Kalimantan Timur'), ('Kalimantan Utara', 'Kalimantan Utara'), ('Sulawesi Utara', 'Sulawesi Utara'), ('Sulawesi Tengah', 'Sulawesi Tengah'), ('Sulawesi Selatan', 'Sulawesi Selatan'), ('Sulawesi Tenggara', 'Sulawesi Tenggara'), ('Gorontalo', 'Gorontalo'), ('Sulawesi Barat', 'Sulawesi Barat'), ('Maluku', 'Maluku'), ('Maluku Utara', 'Maluku Utara'), ('Papua Barat', 'Papua Barat'), ('Papua', 'Papua'), ('Papua Tengah', 'Papua Tengah'), ('Papua Pegunungan', 'Papua Pegunungan'), ('Papua Selatan', 'Papua Selatan'), ('Papua Barat Daya', 'Papua Barat Daya')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
