# Generated by Django 5.1.3 on 2024-12-18 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Espresso'), ('ML', 'Americano'), ('LS', 'Latte'), ('MS', 'Cappuccino'), ('PN', 'Mocha'), ('GH', 'Macchiato'), ('CZ', 'Flat White'), ('IC', 'Cold Brew')], max_length=2),
        ),
    ]
